### ISSUE TITLE
Extendable hamburger menu issue with WP 6.4.1

### ISSUE THREAD

**Issue by arturgrabo** [extendify/extendable#127]
@amjadr360 - someone reported this through support chat:

> There seems to be a problem with the extendable theme and WP 6.4.1
>  The hamburger menu is not working on mobile. The menu itself stays invisible when clicking the icon. 

I asked for additional info but haven't heard back. Can you please take a look?

**Comment by arturgrabo** [comment]
Turns out it was our partner Mijndomein reporting the issue. They followed up today with an email and here is more info:

> There seems to be a bug that is related to the Extendable theme and WP 6.4.1
> The Hamburger menu on mobile sizes is not working. Well the hamburger menu icon shows up, but when you click on it the menu itself doesn't show up.
> 
> On my desktop i checked with the dev-tools in chrome, and when I slightly resize the window to make it bigger then the menu pops up.
> 
> So probably something to do with margins or something idk?
> Is this something that you are aware of and working on?
> 
> Few examples of sites where you can see this problem "in action";
> [intotheworld.agency](http://intotheworld.agency/)
> [groeisaam.nu](http://groeisaam.nu/)
> [uucga.com](http://uucga.com/)

**Comment by amjadr360** [comment]
Resolved this issue in this [PR](https://github.com/extendify/extendable/pull/128)

**Comment by arturgrabo** [comment]
When do you think we'll release this?

**Comment by amjadr360** [comment]
> When do you think we'll release this?

We will release this today.

**Comment by amjadr360** [comment]
The theme has been released.

**Comment by arturgrabo** [comment]
thanks
