### ISSUE TITLE
Make all fonts available to all style variations

### ISSUE THREAD

**Issue by luminuu** [extendify/extendable#70]
While clicking through the different style variations today I noticed that the fonts which reside in `assets/fonts` are only available to the specific style variation. To further improve the individualisation, I thought of making all fonts available in all variations, so the user can swap the fonts if they prefer to have them with another color palette.

I did a test on my local environment by adding all available fonts to the general theme.json file. However these fonts then only show up on the default style, so the list of fonts has to be added to each style variation. Keeping this list up to date in the future could be a bit challenging.

I've looked at the Gutenberg repository, currently there is no discussion to provide a set of fonts "globally" in a theme to all style variations. I guess that's a use case no one hasn't come across yet.

**Comment by colorful-tones** [comment]
I think this is one of those areas where making decisions (and not options) is best. If we add all the fonts in the parent `theme.json`. Then this sets the user up to chose a new font for _everything_, which could potentially give them the keys to make some ugly looking stuff _and_ have a bunch of additional font calls per page load.

Each style variation represents: typography, colors, and small layout changes. So, fonts are part of those package.

I've been mirroring what the Automattic team has been doing. For example, [Pendant](https://github.com/Automattic/themes/tree/trunk/pendant), [Archeo](https://github.com/Automattic/themes/tree/trunk/archeo) and [Remote](https://github.com/Automattic/themes/tree/trunk/remote)

**Comment by richtabor** [comment]
> and have a bunch of additional font calls per page load.

This is what I'm more concerned about. Do the font calls happen regardless of if the font is used on a page?

**Comment by colorful-tones** [comment]
A little discovery that I wanted to share.

Currently, both the [`theme.json`](https://github.com/extendify/extendable/blob/main/theme.json#L171) and [`styles/gdansk.json`](https://github.com/extendify/extendable/blob/main/styles/gdansk.json#L194) both have Inter as their `"slug": "body"` font:

```
	{
		"fontFamily": "\"Inter\", sans-serif",
		"name": "Body",
		"slug": "body",
		"fontFace": [
			{
				"fontDisplay": "block",
				"fontFamily": "Inter",
				"fontStretch": "normal",
				"fontStyle": "normal",
				"fontWeight": "100 800",
				"src": [
					"file:./assets/fonts/Inter/Inter-VariableFont_slnt,wght.woff2"
				]
			}
		]
	}
```

If I remove the entry from Gdansk's `styles/gdansk.json` then it does not fall back to the `theme.json` and no font is queued and served, and just system default fonts.

**Comment by luminuu** [comment]
> This is what I'm more concerned about. Do the font calls happen regardless of if the font is used on a page?

Just checked it on my installation, all fonts get called on the frontend:
![image](https://user-images.githubusercontent.com/7585600/173908146-652997f1-53b1-43e0-9b21-b19d348122ad.png)

This, along with Damon's comment it makes no sense looking further into this. I thought the Webfont API was better developed, but apparently it's not.

> If I remove the entry from Gdansk's `styles/gdansk.json` then it does not fall back to the `theme.json` and no font is queued and served, and just system default fonts.

That is similar behaviour to my finding that you have to add all fonts to all style variations to make them available everywhere - so each style variation is it's very own theme.json, but with a different name bundled together in one theme.

**Comment by luminuu** [comment]
Interesting, I wasn't aware of that.

**Comment by clubkert** [comment]
Potentially a relevant thread: https://twitter.com/ellenbauer/status/1539106085507936260?t=FnN4ntKKVh8XG-TTeutBFQ&s=19

**Comment by amjadr360** [comment]
Made all fonts available to all style variations in this PR: https://github.com/extendify/extendable/pull/117. Just a heads-up: even if many fonts are in the <style> tag, the browser will only download the ones actually used on the page.
