### ISSUE TITLE
Add `"block-styles"` theme tag

### ISSUE THREAD

**Issue by dgwyer** [extendify/extendable#81]
Just noticed that Extendable doesn't include the `"block-styles"` tag. I think this should be added in the `style.css` header?

**Comment by richtabor** [comment]
Is that an official tag? 

<img width="1002" alt="CleanShot 2022-06-22 at 13 52 31@2x" src="https://user-images.githubusercontent.com/1813435/175104097-4a3a7859-7e41-4682-b44a-30f41f65ab70.png">

**Comment by dgwyer** [comment]
Yep. :)

https://make.wordpress.org/themes/handbook/review/required/theme-tags/#features-tags

**Comment by richtabor** [comment]
Looks like this tag is for r[egistered block styles](https://richtabor.com/block-styles/). 
![CleanShot 2022-06-24 at 11 04 40@2x](https://user-images.githubusercontent.com/1813435/175563421-54a4f3e5-4414-4d7e-9bed-ddf557dc1e83.png)

**Comment by dgwyer** [comment]
Doesn't this tag include the core block style definitions in theme.json?

**Comment by richtabor** [comment]
I'm pretty sure it's for just the registered styles 🤷  — def one of those fringes that are not 100% solid rn.
