### ISSUE TITLE
Menu items have no spacing in site editor

### ISSUE THREAD

**Issue by clubkert** [extendify/extendable#97]
In the site editor, our menu items appear to not have the correct spacing. They look fine on the front end.

### Site editor

![Screenshot 2022-11-17 at 12 04 32 PM](https://user-images.githubusercontent.com/2229643/202535831-687554f9-9b3b-413c-9059-5d187b44e0ff.png)

### Front end

![Screenshot 2022-11-17 at 12 04 49 PM](https://user-images.githubusercontent.com/2229643/202535849-a3fbc6d8-d85d-4d8c-94cc-0e0fe5f4005e.png)

**Comment by amjadr360** [comment]
This issue was solved in this [PR](https://github.com/extendify/extendable/pull/96).
